### ISSUE TITLE
Update gallery

### ISSUE THREAD

**Issue by ceball** [pyviz-dev/nbsite#1]
Currently, it's just about hacked to not error out when it runs.

### Alternatives to consider?
* ? http://sphinx-nbexamples.readthedocs.io/en/dev/
* ...?

**Comment by ceball** [comment]
For 'tmphvdocs', on mac locally I get gallery images for bokeh. But don't get them on linux/travis:

<img width="531" alt="screen shot 2017-11-26 at 2 09 24 pm" src="https://user-images.githubusercontent.com/1929/33240767-7399d152-d2b3-11e7-8206-9f4cf3d67474.png">


<img width="1165" alt="screen shot 2017-11-26 at 2 08 27 pm" src="https://user-images.githubusercontent.com/1929/33240761-61fe536e-d2b3-11e7-9565-fe8e7b9b87dc.png">

**Comment by ceball** [comment]
The gallery's kind of working now (see e.g. https://ioam-docs.github.io/geoviews-master/gallery/index.html).

Need to simplify running it, add back support for reference gallery (for hv), and probably some other stuff. In any case, the next step should be to update the 'holoviews with nbsite' project (https://github.com/ContinuumIO/tmphvdocs) to use the latest version of nbsite to generate a gallery like holoviews'.

**Comment by jbednar** [comment]
The gallery looks great!  

I've always thought it was confusing to have "gallery" and "reference gallery", as the relationship between those two has never been clear.  Maybe "app gallery" and "example gallery"?  Or should we revisit the decision to have them separated in the first place?

**Comment by jbednar** [comment]
![image](https://user-images.githubusercontent.com/1695496/34962114-0ffa1590-fa08-11e7-8d32-b28a6c1089b4.png)

The hv gallery spacing has always looked odd to me.  Would it be possible to have a constant height, but variable width, so there isn't so much white space on the page?  A viz tool's gallery ought to be packing the screen with viz!

Or maybe the current shapes would be fine if we were laying things out by column rather than by row, in which case the items in each column should bubble up close to one another to get rid of the whitespace.  Ideally a gallery should be putting as much information in front of eyeballs as possible, so that they eye can flick around and find the right thing, instead of having a manual scrolling process.

**Comment by jbednar** [comment]
Probably in general people make either square or landscape-format plots, and only rarely have long, thin vertical plots, so I think a constant-height rule would make a good default.

**Comment by jsignell** [comment]
I think the gallery is looking pretty reasonable now.

**Comment by jbednar** [comment]
Yes, it looks great!
