### ISSUE TITLE
Nbsite doesn't render pure matplotlib

### ISSUE THREAD

**Issue by jsignell** [pyviz-dev/nbsite#151]
I am running into this when trying to work on more "real" pyviz projects. For instance contrib_colormaps. Matplotlib plots render fine when holoviews is involved, but when it is a pure matplotlib call, they don't seem to render. I will try to make an example in nbsite to show the behavior.

**Comment by ceball** [comment]
The "docs" not very helpfully say this under 'prerequisites' for using nbsite:
> 6. You are using holoviews for visualization (other packages might work, or not having holoviews might work, but currently untested; if you don't have holoviews, you will at least need to override nbbuild_ipython_startup in nbbuild.py, setting it to e.g. "").

I don't know what that means you should do exactly. But if I needed to hack matplotlib examples to work right now, I'd probably start by seeing what happens if you add something like `get_ipython.run_line_magic('matplotlib','inline')` in https://github.com/pyviz-dev/nbsite/blob/master/nbsite/ipystartup.py. (Or whatever `%matplotlib ...` variant it should be.)

If not that, at least that file is somewhere you could do something. From memory, that's where you get to inject code into the kernel to confuse everyone. Otherwise you'll get the same as you do if you just run nbconvert on your notebook (which presumably also doesn't render your matplotlib plots...?).

**Comment by jsignell** [comment]
Ah thanks for pointing that out for me :) I've definitely read that sentence before but I thought it was just saying that holoviews needs to be available, not that it is the only tested means of plotting.

**Comment by jbednar** [comment]
Matplotlib plots work fine here: https://panel.pyviz.org/getting_started/index.html

**Comment by jsignell** [comment]
Ok so maybe the issue I'm seeing is more nuanced. This gives me some good places to start :)

**Comment by ceball** [comment]
I'm not at a computer, so can't check, but either the notebook Jim linked
to has a %matplotlib inline (or similar) in it, or nbsite is called/used in
a special way, or nbsite is modified and I haven't noticed (I guess I
didn't look at it for a year, so highly possible!).

I assumed your notebooks didn't have %matplotlib inline in them or you
wouldn't be having a problem. Maybe they do? Then I'd be surprised if
they're not working.

If they have e.g. %matplotib notebook in, they might well not work. I can't
remember the matplotlib backend details any more (there are some
interactive ones, right? which might not work with nbconvert without some
more effort...?).

**Comment by jbednar** [comment]
Yes, that example does use %matplotlib inline.  I don't know if any other options (ipympl, webagg, %matplotlib notebook, etc.) would work, but it would be of course great if they do!  I think it's down to what nbconvert does with them...

**Comment by jsignell** [comment]
I think I'm cracking up. It works totally fine when `%matplotlib inline` is included (as it should be). Sorry for the noise.

**Comment by jbednar** [comment]
Can you please update nbsite's docs to explain that?

**Comment by ceball** [comment]
I guess the docs would link to nbconvert or some place that discusses issues like this? (I'm not sure what that place is.)

If it's not generally possible to have nbconvert work without people having to alter their notebooks (e.g. say they have to use matplotlib inline for nbconvert, but that isn't what they actually want/had in their notebook), maybe nbsite could do something?

Or if nbconvert makes it possible via options, we might need to expose them.

Otherwise whatever matplotlib option was being used would need to be fixed to support conversion by nbconvert, i.e. returning whatever info is needed for nbconvert to render (vs the browser).

**Comment by jbednar** [comment]
I don't think we need any extreme measures, we just need to update the nbsite docs to clarify the current misleading text that makes it seem like it works only for holoviews; it also works for `%matplotlib inline` and for bokeh, and possibly for plotly (if the nbsite-rendered holoviews plotly docs mean that plotly works too).  That's pretty good coverage of the most popular libraries already.

**Comment by ceball** [comment]
No extreme measures is fine, but I think linking to nbconvert's coverage of this topic (if any)/pointing out it will only work wherever nbconvert works would be useful. And it will still be necessary to stop https://github.com/pyviz-dev/nbsite/blob/master/nbsite/ipystartup.py from being imported if you don't have holoviews, since that file imports holoviews. The docs hint how to do it, but I haven't tried/it might be out of date.

**Comment by ceball** [comment]
Or that could be fixed :) Not sure if it's the only place where holoviews is assumed.
