### ISSUE TITLE
Update to nbconvert 6 (nbclient)

### ISSUE THREAD

**Issue by ceball** [pyviz-dev/nbsite#189]
We're on 5 for now (#187).

It's probably easy, but a better investment of time might be figuring out if parts of nbsite can be replaced internally by an alternative tool (#2, #174) or if it can be replaced entirely (#68).

**Comment by maximlt** [comment]
@philippjfr I'd like to update `nbsite` to support `nbconvert` 6 (and maybe even 7 since it has release candidates, but one thing at a time).

Do you know why `ExecutePreprocessor` had to be subclassed? Asking you since apparently you overwrote `handle_comm_msg`.

https://github.com/pyviz-dev/nbsite/blob/fe2cded1cfc3519b6c423cd55f52ebc044fabb91/nbsite/nbbuild.py#L62-L87

**Comment by philippjfr** [comment]
We were getting weird errors about the comm being broken for any pyviz_comms based output afaik. Might be possible to fix that to replace the jupyter comm with the Comm baseclass when building the docs I suppose.
